# Do not edit this file.  It is generated from:
#    /scratch2/NCEPDEV/climate/Hyun-Chul.Lee/DATM-MOM6-CICE5-v3/coupled_DATM_MOM6_CICE.appBuilder
# Edit that file instead.
COMPONENTS ?= FMS DATM MOM6 CICE
DATM_BINDIR ?= /scratch2/NCEPDEV/climate/Hyun-Chul.Lee/DATM-MOM6-CICE5-v3/DATM/DATM_INSTALL
DATM_SRCDIR ?= /scratch2/NCEPDEV/climate/Hyun-Chul.Lee/DATM-MOM6-CICE5-v3/DATM/DATM
MOM6_BINDIR ?= /scratch2/NCEPDEV/climate/Hyun-Chul.Lee/DATM-MOM6-CICE5-v3/MOM6/MOM6_INSTALL
CICE_BINDIR ?= /scratch2/NCEPDEV/climate/Hyun-Chul.Lee/DATM-MOM6-CICE5-v3/CICE/CICE_INSTALL
